export {default as Home} from "./Home";
export {default as Login} from "./Login";
export {default as Register} from "./Register";
export {default as Activities} from "./Activities";
export {default as Routines} from "./Routines";
export {default as MyRoutines} from "./MyRoutines";
export {default as NavBar} from "./NavBar";
export {default as CreateRoutine} from "./CreateRoutine";
export {default as EditRoutine} from "./EditRoutine"
